### PR TITLE
Add CESM2-LE zarrification files

### PR DESCRIPTION
**Pull request by mgrover1**
Ensure workflow is documented, including all relevant files

### CODE REVIEW

**Comment by andersy005** [comment]
Thanks, Max! Could we keep this in https://github.com/NCAR/cesm2-le-aws? I like what you've done with the repository, and It would be useful to have everything there... What do you think?

**Comment by mgrover1** [comment]
Sure - should we have this in both repos? I can update this here, and just copy over the same files.... I know that would mean duplication, but I figured it would be helpful to have this here with the rest of the examples... what do you think?

**Comment by andersy005** [comment]
I'm in favor of avoiding code duplication so as to avoid having one of the versions going stale.. but I'll leave the final decision to you :)

**Comment by mgrover1** [comment]
Sounds good! I will go ahead and migrate this to that project repo - that way, the docs, zarrification, and everything is one place!

**Pull request closed without merging**
